"""add size to products table

Revision ID: 269b5d25f9d1
Revises: ced0827c252b
Create Date: 2026-05-22 07:30:17.734052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269b5d25f9d1'
down_revision: Union[str, Sequence[str], None] = 'ced0827c252b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.String(), nullable=True))
    op.alter_column('products', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'size')
    # ### end Alembic commands ###
