"""add shipping address column

Revision ID: 3683627542ed
Revises: 682f76615bab
Create Date: 2026-05-20 18:08:18.579244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3683627542ed'
down_revision: Union[str, Sequence[str], None] = '682f76615bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.String(), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
