"""add crypto payment fields

Revision ID: 682f76615bab
Revises: c02ab56843aa
Create Date: 2026-05-20 17:02:17.655226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '682f76615bab'
down_revision: Union[str, Sequence[str], None] = 'c02ab56843aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(), server_default='card', nullable=False))
    op.add_column('orders', sa.Column('crypto_currency', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('crypto_network', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('crypto_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'crypto_tx_hash')
    op.drop_column('orders', 'crypto_network')
    op.drop_column('orders', 'crypto_currency')
    # op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
