"""Upgrade user model for roles, dates, and VIP spending

Revision ID: c02ab56843aa
Revises: cfbb002d7d62
Create Date: 2026-05-01 23:02:00.534957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c02ab56843aa'
down_revision: Union[str, Sequence[str], None] = 'cfbb002d7d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('total_spent', sa.Float(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'STAFF', 'CUSTOMER', name='roleenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'STAFF', 'CUSTOMER', name='roleenum'),
               existing_nullable=False)
    op.drop_column('users', 'total_spent')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
